theme = "ayu_mirage"
# theme = "nord-night" 

[editor]
line-number = "relative"
mouse = true
middle-click-paste = true
auto-completion = true
color-modes = true
bufferline = "multiple"
cursorline = true
rulers = [ 120 ]
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
character = "|"
render = true
